controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController

ackermann_steering_controller:
  ros__parameters:
    use_sim_time: true
    
    # Joint Names
    rear_wheels_names: ['rear_left_wheel_joint', 'rear_right_wheel_joint']
    front_wheels_names: ['front_left_steer_joint', 'front_right_steer_joint']

    # Interface Types
    drive_interface_name: velocity
    steering_interface_name: position

    # Geometry
    wheelbase: 0.6
    # UPDATED: Matched to new URDF track width to prevent flipping
    front_wheel_track: 0.6
    rear_wheel_track: 0.6
    front_wheels_radius: 0.125
    rear_wheels_radius: 0.125
    
    # Odometry
    open_loop: true
    # UPDATED: Base footprint is the new root
    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    enable_odom_tf: true

    # Constraints
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 2.0